baseURL = 'https://madhavrkumar.com'
languageCode = 'en-us'

title = 'Madhav Kumar'
author = 'Madhav Kumar'
theme = 'smol-cat'


[params]
    dateFmt = "2006-01-02"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20

  [[menu.main]]
    identifier = "art"
    name = "Art"
    url = "/art"
    weight = 30

  [[menu.footer]]
    name = "RSS"
    url = "/index.xml"
    weight = 10

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/MadhavRKumar"
    weight = 20

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/madhav-ramesh-kumar/"
    weight = 30

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
    wrapperClass = 'highlight'
  
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

