baseURL = 'https://madhavrkumar.com'
languageCode = 'en-us'

title = 'Madhav Kumar'
author = 'Madhav Kumar'
theme = 'smol-dark'


[params]
    subtitle = "???"
    dateFmt = "2006-01-02"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post"
    weight = 20

  [[menu.main]]
    identifier = "art"
    name = "Art"
    url = "/art"
    weight = 30

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/MadhavRKumar"
    weight = 1

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/madhav-ramesh-kumar/"
    weight = 2



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
    wrapperClass = 'highlight'


