baseURL = 'https://madhavrkumar.com'
languageCode = 'en-us'

title = 'Madhav Kumar'
author = 'Madhav Kumar'
theme = 'smol-dark'

sectionPagesMenu = "main"


[params]
    subtitle = "???"
    dateFmt = "2006-01-02"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'catppuccin-mocha'
    tabWidth = 4
    wrapperClass = 'highlight'
