baseURL = 'https://madhavrkumar.com'
languageCode = 'en-us'
title = 'Madhav Kumar'
enableGitInfo = true

theme = 'smol-cat'

[params]
    dateFmt = "2006-01-02"
    defaultEmail="madhavrkumar@gmail.com"
    title = 'Madhav Kumar'
    author = 'Madhav Kumar'
    description = "Madhav Kumar's personal website. This is where I share ideas, learnings, and experiments. I talk about software engineering and life in general."

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now"
    weight = 15


  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20

  [[menu.main]]
    identifier = "art"
    name = "Art"
    url = "/art"
    weight = 30

  [[menu.footer]]
    name = "RSS"
    url = "https://subscribeopenly.net/subscribe/?url=https://www.madhavrkumar.com/posts/index.xml"
    weight = 10

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/MadhavRKumar"
    weight = 20

  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/madhav-ramesh-kumar/"
    weight = 30

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 0
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 4
    wrapperClass = 'highlight'
  
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

